version: '3.8'
services:
  zipkin:
    image: openzipkin/zipkin:latest
    ports:
      - "${ZIPKIN_PORT:-9411}:9411" # default 9411
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:9411/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    volumes:
      - ./otel-collector-config.yml:/etc/otel-collector-config.yml
    command: ["--config=/etc/otel-collector-config.yml"]
    ports:
      - "${OTEL_PORT:-4317}:4317" # default 4317
      - "${OTEL_PROM_PORT:-8889}:8889" # default 8889
    depends_on:
      - zipkin
    environment:
      - LOG_LEVEL=debug

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "${PROMETHEUS_PORT:-9090}:9090" # default 9090
    healthcheck:
      test: ["CMD", "wget", "--spider", "--quiet", "http://localhost:9090/-/healthy"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - otel-collector

  grafana:
    image: grafana/grafana:latest
    ports:
      - "${GRAFANA_PORT:-3000}:3000" # default 3000
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:3000/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./grafana-dashboard-api-test-observability.json:/etc/grafana/provisioning/dashboards/grafana-dashboard-api-test-observability.json
      - ./grafana-dashboard-provisioning.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus

  pushgateway:
    image: prom/pushgateway:latest
    ports:
      - "${PUSHGATEWAY_PORT:-9091}:9091" # default 9091
    healthcheck:
      test: ["CMD", "wget", "--spider", "--quiet", "http://localhost:9091/-/healthy"]
      interval: 10s
      timeout: 5s
      retries: 5