version: '3.8'
services:
  zipkin:
    image: openzipkin/zipkin:latest
    ports:
      - "9411:9411"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:9411/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    volumes:
      - ./otel-collector-config.yml:/etc/otel-collector-config.yml
    command: ["--config=/etc/otel-collector-config.yml"]
    ports:
      - "4317:4317"
      - "8889:8889" # Prometheus metrics endpoint (default for otelcol-contrib)
    depends_on:
      - zipkin
    environment:
      - LOG_LEVEL=debug

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    healthcheck:
      test: ["CMD", "wget", "--spider", "--quiet", "http://localhost:9090/-/healthy"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - otel-collector

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:3000/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./grafana-dashboard-api-test-observability.json:/etc/grafana/provisioning/dashboards/grafana-dashboard-api-test-observability.json
      - ./grafana-dashboard-provisioning.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus

  pushgateway:
    image: prom/pushgateway:latest
    ports:
      - "9091:9091"
    healthcheck:
      test: ["CMD", "wget", "--spider", "--quiet", "http://localhost:9091/-/healthy"]
      interval: 10s
      timeout: 5s
      retries: 5