name: API Test CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest
    services:
      zipkin:
        image: openzipkin/zipkin:2.23
        ports:
          - 9411:9411
      otel-collector:
        image: otel/opentelemetry-collector-contrib:latest
        ports:
          - 4317:4317  # OTLP gRPC
          - 55681:55681 # OTLP HTTP
        volumes:
          - ./otel-collector-config.yml:/etc/otelcol/config.yaml
      prometheus:
        image: prom/prometheus:latest
        ports:
          - 9090:9090
        volumes:
          - ./prometheus.yml:/etc/prometheus/prometheus.yml
      grafana:
        image: grafana/grafana:latest
        ports:
          - 3000:3000
        volumes:
          - ./grafana-dashboard-api-test-observability.json:/etc/grafana/provisioning/dashboards/grafana-dashboard-api-test-observability.json
          - ./grafana-dashboard-provisioning.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
    env:
      MAVEN_OPTS: "-Dmaven.repo.local=${{ github.workspace }}/repository"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://localhost:4317"
      SERVICE_NAME: "api-test-automation"
      TEST_RUN_ID: ${{ github.run_id }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check prometheus.yml exists and is a file
        run: |
          ls -l ./prometheus.yml
          file ./prometheus.yml

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      - name: Run tests with instrumentation
        run: mvn clean test
        env:
          OTEL_EXPORTER_OTLP_ENDPOINT: "http://localhost:4317"
          SERVICE_NAME: "api-test-automation"
          TEST_RUN_ID: ${{ github.run_id }}

      - name: Confirm Zipkin is running
        run: |
          curl --fail http://localhost:9411/health || exit 1
          echo "Zipkin is up!"

      - name: Verify traces in Zipkin
        run: |
          curl -s http://localhost:9411/api/v2/traces?serviceName=api-test-automation | jq .

      - name: Confirm Prometheus is running
        run: |
          curl --fail http://localhost:9090/-/healthy || exit 1
          echo "Prometheus is up!"

      - name: Verify test metrics in Prometheus
        run: |
          sleep 10 # Give Prometheus time to scrape metrics
          curl -s "http://localhost:9090/api/v1/query?query=test_result_total" | jq .
          # Fail if no results
          curl -s "http://localhost:9090/api/v1/query?query=test_result_total" | grep '"status":"success"' || exit 1
          echo "Prometheus metrics found!"

      - name: Confirm Grafana is running
        run: |
          curl --fail http://localhost:3000/api/health || exit 1
          echo "Grafana is up!"

      - name: Verify Grafana dashboard is present
        run: |
          sleep 10 # Give Grafana time to provision dashboards
          curl -s -u admin:admin "http://localhost:3000/api/search?query=API%20Test%20Observability" | grep 'API Test Observability' || exit 1
          echo "Grafana dashboard found!"